[project]
name = "minicc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual[syntax]>=6.5.0",
    "textual-dev>=1.8.0",
]
